package org.rommert.adventofcode2021.day2;

import org.rommert.adventofcode2021.InputParser;

import java.util.List;
import java.util.Vector;
import java.util.function.Function;

public class SubmarineMoves {

    static String inputString = "forward 2\n" +
            "forward 5\n" +
            "forward 5\n" +
            "down 4\n" +
            "forward 8\n" +
            "down 1\n" +
            "forward 2\n" +
            "forward 2\n" +
            "down 9\n" +
            "down 2\n" +
            "forward 6\n" +
            "forward 3\n" +
            "down 9\n" +
            "down 2\n" +
            "forward 4\n" +
            "up 2\n" +
            "forward 7\n" +
            "up 6\n" +
            "forward 8\n" +
            "forward 4\n" +
            "up 5\n" +
            "forward 3\n" +
            "down 9\n" +
            "forward 5\n" +
            "forward 8\n" +
            "forward 6\n" +
            "forward 6\n" +
            "forward 8\n" +
            "forward 8\n" +
            "forward 5\n" +
            "down 2\n" +
            "forward 8\n" +
            "down 4\n" +
            "down 6\n" +
            "down 6\n" +
            "forward 7\n" +
            "forward 6\n" +
            "up 3\n" +
            "up 5\n" +
            "down 5\n" +
            "down 3\n" +
            "up 2\n" +
            "down 7\n" +
            "down 2\n" +
            "forward 1\n" +
            "forward 6\n" +
            "up 1\n" +
            "down 7\n" +
            "forward 8\n" +
            "down 7\n" +
            "down 6\n" +
            "forward 5\n" +
            "up 6\n" +
            "forward 9\n" +
            "down 9\n" +
            "up 3\n" +
            "down 6\n" +
            "down 1\n" +
            "forward 6\n" +
            "up 1\n" +
            "down 1\n" +
            "up 3\n" +
            "up 7\n" +
            "forward 1\n" +
            "down 5\n" +
            "forward 7\n" +
            "forward 3\n" +
            "down 9\n" +
            "up 8\n" +
            "forward 1\n" +
            "down 4\n" +
            "up 1\n" +
            "forward 9\n" +
            "forward 7\n" +
            "down 2\n" +
            "forward 8\n" +
            "down 2\n" +
            "down 5\n" +
            "down 2\n" +
            "up 1\n" +
            "down 5\n" +
            "forward 4\n" +
            "forward 8\n" +
            "forward 3\n" +
            "forward 3\n" +
            "forward 1\n" +
            "down 1\n" +
            "forward 1\n" +
            "down 7\n" +
            "up 7\n" +
            "down 3\n" +
            "down 1\n" +
            "down 7\n" +
            "down 4\n" +
            "forward 7\n" +
            "forward 5\n" +
            "down 9\n" +
            "down 5\n" +
            "forward 3\n" +
            "up 7\n" +
            "down 2\n" +
            "up 1\n" +
            "forward 1\n" +
            "forward 2\n" +
            "down 7\n" +
            "down 3\n" +
            "forward 7\n" +
            "up 4\n" +
            "forward 3\n" +
            "up 8\n" +
            "down 9\n" +
            "down 4\n" +
            "forward 5\n" +
            "forward 6\n" +
            "down 3\n" +
            "down 5\n" +
            "down 4\n" +
            "down 9\n" +
            "down 8\n" +
            "forward 6\n" +
            "down 3\n" +
            "down 1\n" +
            "down 9\n" +
            "down 6\n" +
            "forward 9\n" +
            "forward 2\n" +
            "up 5\n" +
            "forward 5\n" +
            "forward 4\n" +
            "down 9\n" +
            "up 7\n" +
            "up 2\n" +
            "forward 1\n" +
            "forward 8\n" +
            "forward 6\n" +
            "up 8\n" +
            "down 9\n" +
            "down 2\n" +
            "forward 7\n" +
            "down 6\n" +
            "forward 7\n" +
            "up 9\n" +
            "up 7\n" +
            "down 8\n" +
            "up 1\n" +
            "forward 2\n" +
            "forward 9\n" +
            "down 9\n" +
            "forward 6\n" +
            "down 2\n" +
            "down 1\n" +
            "up 3\n" +
            "forward 4\n" +
            "down 3\n" +
            "down 4\n" +
            "down 9\n" +
            "up 8\n" +
            "up 8\n" +
            "forward 3\n" +
            "up 7\n" +
            "forward 9\n" +
            "forward 7\n" +
            "up 2\n" +
            "up 8\n" +
            "forward 2\n" +
            "down 6\n" +
            "forward 3\n" +
            "forward 1\n" +
            "down 7\n" +
            "down 2\n" +
            "forward 9\n" +
            "forward 9\n" +
            "down 3\n" +
            "forward 2\n" +
            "forward 8\n" +
            "down 6\n" +
            "forward 6\n" +
            "forward 5\n" +
            "forward 1\n" +
            "forward 6\n" +
            "down 8\n" +
            "down 7\n" +
            "up 9\n" +
            "down 6\n" +
            "up 7\n" +
            "down 2\n" +
            "up 8\n" +
            "up 8\n" +
            "down 3\n" +
            "down 7\n" +
            "up 2\n" +
            "up 2\n" +
            "down 6\n" +
            "down 6\n" +
            "forward 2\n" +
            "down 6\n" +
            "forward 8\n" +
            "forward 9\n" +
            "down 3\n" +
            "forward 6\n" +
            "down 9\n" +
            "forward 1\n" +
            "up 6\n" +
            "down 3\n" +
            "up 5\n" +
            "forward 9\n" +
            "forward 7\n" +
            "forward 9\n" +
            "forward 5\n" +
            "up 6\n" +
            "down 3\n" +
            "down 3\n" +
            "down 3\n" +
            "forward 1\n" +
            "up 5\n" +
            "forward 3\n" +
            "forward 2\n" +
            "down 1\n" +
            "forward 7\n" +
            "down 1\n" +
            "forward 6\n" +
            "forward 5\n" +
            "forward 9\n" +
            "up 6\n" +
            "forward 1\n" +
            "up 8\n" +
            "down 7\n" +
            "forward 6\n" +
            "forward 3\n" +
            "forward 1\n" +
            "up 6\n" +
            "forward 4\n" +
            "up 6\n" +
            "down 7\n" +
            "forward 8\n" +
            "forward 4\n" +
            "forward 6\n" +
            "forward 5\n" +
            "up 6\n" +
            "down 7\n" +
            "up 9\n" +
            "down 7\n" +
            "forward 3\n" +
            "down 7\n" +
            "forward 6\n" +
            "down 6\n" +
            "down 6\n" +
            "forward 8\n" +
            "up 8\n" +
            "forward 8\n" +
            "forward 2\n" +
            "down 8\n" +
            "forward 4\n" +
            "forward 9\n" +
            "forward 7\n" +
            "down 4\n" +
            "down 7\n" +
            "forward 4\n" +
            "forward 3\n" +
            "forward 2\n" +
            "forward 2\n" +
            "forward 5\n" +
            "down 6\n" +
            "forward 1\n" +
            "forward 6\n" +
            "up 8\n" +
            "up 3\n" +
            "up 9\n" +
            "forward 3\n" +
            "up 8\n" +
            "forward 3\n" +
            "up 8\n" +
            "down 9\n" +
            "up 7\n" +
            "forward 9\n" +
            "forward 1\n" +
            "down 7\n" +
            "forward 9\n" +
            "down 6\n" +
            "forward 4\n" +
            "down 3\n" +
            "up 9\n" +
            "forward 5\n" +
            "down 4\n" +
            "up 6\n" +
            "down 1\n" +
            "up 9\n" +
            "forward 2\n" +
            "up 2\n" +
            "down 1\n" +
            "forward 7\n" +
            "down 6\n" +
            "down 4\n" +
            "down 7\n" +
            "down 4\n" +
            "down 8\n" +
            "up 9\n" +
            "down 6\n" +
            "up 3\n" +
            "down 7\n" +
            "forward 3\n" +
            "forward 1\n" +
            "down 1\n" +
            "forward 2\n" +
            "forward 6\n" +
            "down 6\n" +
            "forward 5\n" +
            "down 8\n" +
            "down 8\n" +
            "down 6\n" +
            "down 9\n" +
            "forward 6\n" +
            "forward 7\n" +
            "up 8\n" +
            "forward 5\n" +
            "up 8\n" +
            "down 6\n" +
            "up 3\n" +
            "forward 9\n" +
            "up 9\n" +
            "forward 2\n" +
            "up 6\n" +
            "forward 2\n" +
            "down 8\n" +
            "forward 3\n" +
            "down 5\n" +
            "down 8\n" +
            "up 6\n" +
            "down 3\n" +
            "down 7\n" +
            "down 4\n" +
            "forward 5\n" +
            "forward 8\n" +
            "down 8\n" +
            "forward 6\n" +
            "down 8\n" +
            "up 1\n" +
            "forward 5\n" +
            "down 3\n" +
            "down 2\n" +
            "up 1\n" +
            "forward 3\n" +
            "forward 7\n" +
            "forward 6\n" +
            "forward 9\n" +
            "up 8\n" +
            "down 2\n" +
            "down 1\n" +
            "down 7\n" +
            "forward 4\n" +
            "forward 2\n" +
            "down 9\n" +
            "down 3\n" +
            "down 5\n" +
            "up 6\n" +
            "down 2\n" +
            "forward 8\n" +
            "up 1\n" +
            "up 5\n" +
            "down 6\n" +
            "down 7\n" +
            "forward 3\n" +
            "down 4\n" +
            "up 6\n" +
            "down 9\n" +
            "up 6\n" +
            "down 2\n" +
            "down 2\n" +
            "down 6\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 6\n" +
            "forward 5\n" +
            "forward 6\n" +
            "forward 4\n" +
            "down 6\n" +
            "forward 3\n" +
            "down 9\n" +
            "up 8\n" +
            "forward 2\n" +
            "up 3\n" +
            "forward 1\n" +
            "up 8\n" +
            "forward 1\n" +
            "down 6\n" +
            "down 3\n" +
            "forward 5\n" +
            "forward 4\n" +
            "down 9\n" +
            "up 3\n" +
            "down 6\n" +
            "forward 4\n" +
            "down 8\n" +
            "down 3\n" +
            "down 7\n" +
            "forward 1\n" +
            "forward 2\n" +
            "forward 8\n" +
            "down 2\n" +
            "down 6\n" +
            "up 9\n" +
            "forward 2\n" +
            "forward 4\n" +
            "forward 8\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 7\n" +
            "up 8\n" +
            "forward 1\n" +
            "down 6\n" +
            "down 3\n" +
            "forward 5\n" +
            "forward 5\n" +
            "forward 2\n" +
            "down 2\n" +
            "down 2\n" +
            "down 2\n" +
            "up 4\n" +
            "forward 2\n" +
            "forward 5\n" +
            "forward 1\n" +
            "forward 5\n" +
            "down 3\n" +
            "forward 8\n" +
            "up 1\n" +
            "forward 9\n" +
            "up 5\n" +
            "forward 2\n" +
            "down 4\n" +
            "forward 8\n" +
            "forward 9\n" +
            "up 6\n" +
            "up 1\n" +
            "down 7\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 3\n" +
            "down 3\n" +
            "forward 3\n" +
            "forward 6\n" +
            "up 4\n" +
            "forward 2\n" +
            "down 9\n" +
            "forward 5\n" +
            "forward 3\n" +
            "forward 5\n" +
            "down 6\n" +
            "up 6\n" +
            "down 7\n" +
            "forward 2\n" +
            "down 4\n" +
            "forward 6\n" +
            "forward 5\n" +
            "forward 8\n" +
            "down 4\n" +
            "up 3\n" +
            "up 4\n" +
            "down 9\n" +
            "forward 9\n" +
            "down 7\n" +
            "down 1\n" +
            "down 9\n" +
            "down 6\n" +
            "down 8\n" +
            "forward 7\n" +
            "down 3\n" +
            "up 3\n" +
            "up 5\n" +
            "forward 5\n" +
            "up 6\n" +
            "down 6\n" +
            "forward 9\n" +
            "down 7\n" +
            "forward 6\n" +
            "up 1\n" +
            "forward 7\n" +
            "forward 8\n" +
            "down 9\n" +
            "down 1\n" +
            "forward 4\n" +
            "up 2\n" +
            "down 3\n" +
            "up 3\n" +
            "down 6\n" +
            "forward 6\n" +
            "down 7\n" +
            "down 2\n" +
            "forward 8\n" +
            "forward 2\n" +
            "forward 3\n" +
            "forward 5\n" +
            "up 8\n" +
            "up 6\n" +
            "down 1\n" +
            "up 7\n" +
            "down 1\n" +
            "down 8\n" +
            "forward 5\n" +
            "up 7\n" +
            "down 1\n" +
            "forward 8\n" +
            "down 6\n" +
            "down 2\n" +
            "up 7\n" +
            "down 1\n" +
            "forward 1\n" +
            "up 8\n" +
            "forward 5\n" +
            "down 7\n" +
            "down 8\n" +
            "forward 4\n" +
            "down 6\n" +
            "down 2\n" +
            "forward 4\n" +
            "forward 7\n" +
            "down 5\n" +
            "down 1\n" +
            "down 8\n" +
            "down 3\n" +
            "up 8\n" +
            "down 6\n" +
            "down 1\n" +
            "down 1\n" +
            "forward 4\n" +
            "down 8\n" +
            "up 5\n" +
            "forward 3\n" +
            "forward 3\n" +
            "forward 5\n" +
            "forward 8\n" +
            "up 7\n" +
            "forward 5\n" +
            "down 8\n" +
            "forward 9\n" +
            "up 9\n" +
            "forward 1\n" +
            "down 2\n" +
            "up 9\n" +
            "down 7\n" +
            "up 1\n" +
            "up 3\n" +
            "forward 9\n" +
            "forward 8\n" +
            "forward 3\n" +
            "forward 8\n" +
            "down 8\n" +
            "down 5\n" +
            "down 7\n" +
            "up 7\n" +
            "forward 9\n" +
            "up 8\n" +
            "down 9\n" +
            "down 9\n" +
            "down 1\n" +
            "up 4\n" +
            "up 4\n" +
            "up 3\n" +
            "forward 3\n" +
            "down 7\n" +
            "down 3\n" +
            "forward 5\n" +
            "up 9\n" +
            "down 3\n" +
            "up 2\n" +
            "forward 1\n" +
            "forward 4\n" +
            "up 9\n" +
            "forward 6\n" +
            "down 6\n" +
            "down 6\n" +
            "forward 2\n" +
            "forward 2\n" +
            "down 4\n" +
            "forward 9\n" +
            "up 6\n" +
            "down 8\n" +
            "down 8\n" +
            "down 9\n" +
            "up 4\n" +
            "down 9\n" +
            "down 3\n" +
            "down 7\n" +
            "forward 4\n" +
            "up 4\n" +
            "up 5\n" +
            "down 2\n" +
            "up 2\n" +
            "forward 1\n" +
            "up 8\n" +
            "forward 2\n" +
            "down 6\n" +
            "forward 9\n" +
            "down 9\n" +
            "forward 9\n" +
            "up 8\n" +
            "down 5\n" +
            "up 3\n" +
            "up 9\n" +
            "down 8\n" +
            "forward 6\n" +
            "forward 2\n" +
            "forward 7\n" +
            "down 9\n" +
            "down 8\n" +
            "up 9\n" +
            "down 5\n" +
            "up 5\n" +
            "down 1\n" +
            "forward 3\n" +
            "down 2\n" +
            "down 5\n" +
            "down 4\n" +
            "down 1\n" +
            "down 5\n" +
            "down 5\n" +
            "down 5\n" +
            "forward 8\n" +
            "down 2\n" +
            "down 3\n" +
            "down 4\n" +
            "down 2\n" +
            "up 8\n" +
            "up 1\n" +
            "down 5\n" +
            "forward 8\n" +
            "down 6\n" +
            "forward 9\n" +
            "down 6\n" +
            "down 6\n" +
            "down 5\n" +
            "forward 5\n" +
            "forward 3\n" +
            "forward 7\n" +
            "down 6\n" +
            "forward 4\n" +
            "down 8\n" +
            "up 9\n" +
            "up 6\n" +
            "forward 5\n" +
            "down 4\n" +
            "forward 8\n" +
            "forward 1\n" +
            "forward 8\n" +
            "up 5\n" +
            "up 5\n" +
            "forward 6\n" +
            "down 3\n" +
            "down 7\n" +
            "up 7\n" +
            "down 5\n" +
            "forward 1\n" +
            "forward 3\n" +
            "up 3\n" +
            "down 3\n" +
            "down 3\n" +
            "down 5\n" +
            "forward 9\n" +
            "down 2\n" +
            "up 5\n" +
            "up 2\n" +
            "forward 1\n" +
            "down 1\n" +
            "forward 5\n" +
            "down 8\n" +
            "forward 8\n" +
            "forward 9\n" +
            "forward 3\n" +
            "forward 2\n" +
            "forward 4\n" +
            "down 5\n" +
            "up 1\n" +
            "down 5\n" +
            "up 1\n" +
            "up 4\n" +
            "forward 2\n" +
            "forward 4\n" +
            "down 6\n" +
            "up 2\n" +
            "up 4\n" +
            "forward 4\n" +
            "down 7\n" +
            "forward 2\n" +
            "up 1\n" +
            "forward 4\n" +
            "up 4\n" +
            "forward 9\n" +
            "down 1\n" +
            "down 4\n" +
            "up 1\n" +
            "forward 2\n" +
            "forward 3\n" +
            "down 6\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 2\n" +
            "forward 9\n" +
            "up 4\n" +
            "forward 5\n" +
            "forward 2\n" +
            "down 2\n" +
            "forward 5\n" +
            "down 5\n" +
            "down 3\n" +
            "down 7\n" +
            "down 7\n" +
            "up 3\n" +
            "down 7\n" +
            "forward 9\n" +
            "forward 7\n" +
            "up 4\n" +
            "forward 7\n" +
            "up 8\n" +
            "down 8\n" +
            "forward 5\n" +
            "down 2\n" +
            "down 9\n" +
            "up 8\n" +
            "forward 4\n" +
            "forward 4\n" +
            "forward 2\n" +
            "up 4\n" +
            "down 5\n" +
            "forward 3\n" +
            "forward 6\n" +
            "forward 5\n" +
            "forward 3\n" +
            "forward 7\n" +
            "up 9\n" +
            "forward 1\n" +
            "forward 2\n" +
            "up 7\n" +
            "down 4\n" +
            "forward 8\n" +
            "down 2\n" +
            "forward 1\n" +
            "down 1\n" +
            "down 9\n" +
            "up 2\n" +
            "down 2\n" +
            "forward 8\n" +
            "forward 5\n" +
            "up 9\n" +
            "forward 5\n" +
            "down 2\n" +
            "forward 2\n" +
            "down 7\n" +
            "forward 5\n" +
            "down 1\n" +
            "forward 9\n" +
            "forward 8\n" +
            "forward 8\n" +
            "forward 9\n" +
            "forward 8\n" +
            "down 9\n" +
            "forward 8\n" +
            "down 1\n" +
            "down 2\n" +
            "down 9\n" +
            "up 2\n" +
            "forward 8\n" +
            "forward 8\n" +
            "down 9\n" +
            "forward 8\n" +
            "up 8\n" +
            "forward 2\n" +
            "down 5\n" +
            "up 3\n" +
            "forward 2\n" +
            "up 3\n" +
            "down 6\n" +
            "forward 5\n" +
            "up 7\n" +
            "forward 2\n" +
            "forward 7\n" +
            "forward 7\n" +
            "down 8\n" +
            "forward 3\n" +
            "up 5\n" +
            "down 8\n" +
            "down 3\n" +
            "down 8\n" +
            "up 6\n" +
            "down 6\n" +
            "up 4\n" +
            "forward 7\n" +
            "up 6\n" +
            "up 1\n" +
            "down 5\n" +
            "up 8\n" +
            "forward 8\n" +
            "forward 9\n" +
            "down 8\n" +
            "forward 6\n" +
            "down 8\n" +
            "down 9\n" +
            "down 8\n" +
            "forward 9\n" +
            "up 1\n" +
            "down 1\n" +
            "down 8\n" +
            "down 5\n" +
            "down 2\n" +
            "up 7\n" +
            "forward 4\n" +
            "down 4\n" +
            "forward 6\n" +
            "down 1\n" +
            "forward 5\n" +
            "forward 3\n" +
            "forward 9\n" +
            "up 8\n" +
            "down 4\n" +
            "down 6\n" +
            "down 4\n" +
            "down 1\n" +
            "up 9\n" +
            "forward 9\n" +
            "down 9\n" +
            "forward 7\n" +
            "down 2\n" +
            "down 8\n" +
            "forward 2\n" +
            "forward 5\n" +
            "down 6\n" +
            "down 1\n" +
            "down 1\n" +
            "up 3\n" +
            "forward 9\n" +
            "up 7\n" +
            "down 1\n" +
            "down 6\n" +
            "forward 6\n" +
            "up 2\n" +
            "down 4\n" +
            "down 7\n" +
            "forward 3\n" +
            "down 9\n" +
            "down 1\n" +
            "forward 7\n" +
            "forward 2\n" +
            "forward 6\n" +
            "down 4\n" +
            "forward 7\n" +
            "forward 8\n" +
            "forward 3\n" +
            "forward 7\n" +
            "up 8\n" +
            "forward 5\n" +
            "up 8\n" +
            "down 8\n" +
            "forward 3\n" +
            "forward 8\n" +
            "forward 7\n" +
            "forward 3\n" +
            "down 4\n" +
            "forward 9\n" +
            "forward 4\n" +
            "up 6\n" +
            "forward 4\n" +
            "forward 6\n" +
            "up 4\n" +
            "forward 6\n" +
            "forward 2\n" +
            "down 3\n" +
            "down 3\n" +
            "down 4\n" +
            "down 1\n" +
            "down 9\n" +
            "up 1\n" +
            "up 9\n" +
            "down 7\n" +
            "up 9\n" +
            "forward 5\n" +
            "down 2\n" +
            "up 7\n" +
            "forward 9\n" +
            "up 1\n" +
            "down 5\n" +
            "up 8\n" +
            "forward 9\n" +
            "down 1\n" +
            "up 3\n" +
            "forward 3\n" +
            "forward 9\n" +
            "up 7\n" +
            "forward 3\n" +
            "down 7\n" +
            "forward 3\n" +
            "forward 5\n" +
            "forward 4\n" +
            "up 3\n" +
            "forward 3\n" +
            "down 8\n" +
            "forward 7\n" +
            "up 5\n" +
            "forward 9\n" +
            "down 6\n" +
            "up 6\n" +
            "up 1\n" +
            "forward 8\n" +
            "down 9\n" +
            "forward 9\n" +
            "forward 9\n" +
            "down 5\n" +
            "down 7\n" +
            "forward 7\n" +
            "down 5\n" +
            "down 3\n" +
            "forward 4\n" +
            "up 6\n" +
            "forward 6\n" +
            "forward 2\n" +
            "down 8\n" +
            "down 6\n" +
            "forward 1\n" +
            "forward 1\n" +
            "down 6\n" +
            "forward 1\n" +
            "down 6\n" +
            "down 2\n" +
            "forward 1\n" +
            "forward 6\n" +
            "up 4\n" +
            "up 7\n" +
            "up 3\n" +
            "down 6\n" +
            "forward 1\n" +
            "forward 9\n" +
            "forward 4\n" +
            "down 4\n" +
            "forward 3\n" +
            "down 8\n" +
            "down 6\n" +
            "down 6\n" +
            "forward 2\n" +
            "forward 8\n" +
            "forward 6\n" +
            "down 4\n" +
            "up 2\n" +
            "down 1\n" +
            "up 4\n" +
            "down 8\n" +
            "forward 9\n" +
            "down 4\n" +
            "down 8\n" +
            "up 8\n" +
            "forward 2\n" +
            "up 9\n" +
            "down 9\n" +
            "forward 2\n" +
            "down 8\n" +
            "forward 3\n" +
            "down 1\n" +
            "up 9\n" +
            "forward 6\n" +
            "down 9\n" +
            "forward 2\n" +
            "down 2\n" +
            "up 5\n" +
            "down 4\n" +
            "down 5\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 4\n" +
            "forward 6\n" +
            "forward 2\n" +
            "down 8\n" +
            "up 3\n" +
            "up 9\n" +
            "forward 3\n" +
            "forward 6\n" +
            "down 6\n" +
            "down 2\n" +
            "down 5\n" +
            "down 4\n" +
            "forward 1\n" +
            "up 2\n" +
            "down 3\n" +
            "forward 6\n" +
            "forward 5\n" +
            "down 4\n" +
            "down 3\n" +
            "forward 2\n" +
            "forward 4\n" +
            "down 9\n" +
            "down 3\n" +
            "down 4\n" +
            "up 6\n" +
            "forward 8\n" +
            "up 2\n" +
            "up 8\n" +
            "up 4\n" +
            "forward 7\n" +
            "forward 5\n" +
            "forward 9\n" +
            "down 6\n" +
            "forward 7\n" +
            "forward 9\n" +
            "up 3\n" +
            "forward 6\n";

//    static String inputString = "forward 5\n" +
//            "down 5\n" +
//            "forward 8\n" +
//            "up 3\n" +
//            "down 8\n" +
//            "forward 2";

    public static void main(String[] args) {
        List<Command> commands = new InputParser<Command>().convertInput(inputString, createCommand());

        Coordinate finalCoordinate = calculateCoordinates(commands);
        System.out.println(finalCoordinate);
        System.out.println(finalCoordinate.x * finalCoordinate.y * -1); // we calculate coordinate, but final answer requires depth witch *-1's the y-value

    }

    private static Coordinate calculateCoordinates(List<Command> commands) {
        return commands.stream()
                .map(SubmarineMoves::translateToVector)
                .reduce(new Vector(), Vector::add)
                .applyToCoordinate(new Coordinate(0,0));
    }

    private static Vector translateToVector(Command command) {
        switch (command.commandType) {
            case "forward":
                return (new Vector(command.value, 0));
            case "down":
                return (new Vector(0, command.value * -1));
            case "up":
                return new Vector(0, command.value);
            default:
                throw new RuntimeException("unexpected input " + command);
        }
    }

    private static Function<String, Command> createCommand() {
        return cmdString -> new Command(
                cmdString.split(" ")[0],
                Integer.parseInt(cmdString.split(" ")[1]));
    }

    static class Command {
        String commandType;
        int value;

        public Command(String commandType, int value) {
            this.commandType = commandType;
            this.value = value;
        }
    }

    static class Coordinate {
        int x;
        int y;

        public Coordinate(int x, int y) {
            this.x = x;
            this.y = y;
        }

        @Override
        public String toString() {
            return "Coordinate{" +
                    "x=" + x +
                    ", y=" + y +
                    '}';
        }
    }

    static class Vector {
        int x;
        int y;

        public Vector() {}

        public Vector(int x, int y) {
            this.x = x;
            this.y = y;
        }

        public Vector add(Vector vector) {
            return new Vector(x + vector.x, y + vector.y);
        }

        public Coordinate applyToCoordinate(Coordinate coordinate) {
            return new Coordinate(coordinate.x + this.x, coordinate.y + this.y);
        }
    }
}
